# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b67c8911ecd7dd9399a6a7183b2fd9f1fc1c66d63a359b6291d102e16692ad3d1dc5a4c857960acbf4070e0c96e8e74d3e86de6c6a5765fbe79f7694e8282de6

test:
  secret_key_base: 1d82e35266d130243185e5c3a64acd21cd62219440e4db61dfce9287e54c99fb1d77719803edd95d60adc6879522d3437c1068fb5dc22aa0c51cd727b016ca9a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
